server:
  port: 8080
  error:
    path: /error


spring:
  datasource:
    url: jdbc:posgresql://${PROD_DB_HOST}:${PROD_DB_PROT}/${PROD_DB_NAME}
    username: xxx
    password: xxx
      jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        hibernate:
          ddl-auto: update
        show-sql: true
  devtools:
    livereload:
      enabled: true